// <auto-generated />
using System;
using CrewChange.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrewChange.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250623154702_SeedReferenceData")]
    partial class SeedReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrewChange.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High School Diploma",
                            Name = "High School"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Associate's Degree",
                            Name = "Associate's"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bachelor's Degree",
                            Name = "Bachelor's"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Master's Degree",
                            Name = "Master's"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Doctorate Degree",
                            Name = "Doctorate"
                        });
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTerminated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeGroupId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeScheduleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeStatusId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeWorkStatusId")
                        .HasColumnType("int");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<int>("NationalityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PagerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonTerminated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SseExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<bool>("Terminated")
                        .HasColumnType("bit");

                    b.Property<int?>("TerminationReasonId")
                        .HasColumnType("int");

                    b.Property<int>("VeteranStatusTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WorkStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("EmployeeGroupId");

                    b.HasIndex("EmployeeScheduleTypeId");

                    b.HasIndex("EmployeeStatusId");

                    b.HasIndex("EmployeeWorkStatusId");

                    b.HasIndex("GenderTypeId");

                    b.HasIndex("JobId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("NationalityTypeId");

                    b.HasIndex("StateId");

                    b.HasIndex("TerminationReasonId");

                    b.HasIndex("VeteranStatusTypeId");

                    b.HasIndex("WorkStatusId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EmployeeCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeCertifications");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EmployeeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeGroups");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EmployeeScheduleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeScheduleTypes");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EmployeeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Currently employed",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Temporarily away",
                            Name = "On Leave"
                        },
                        new
                        {
                            Id = 3,
                            Description = "No longer employed",
                            Name = "Terminated"
                        });
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.GenderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GenderTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Non-Binary"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Prefer Not to Say"
                        });
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Married"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Divorced"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Widowed"
                        });
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.NationalityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NationalityTypes");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AL",
                            Name = "Alabama"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AK",
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = 50,
                            Abbreviation = "WY",
                            Name = "Wyoming"
                        });
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.TerminationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TerminationReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Employee resigned",
                            Name = "Voluntary"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Position eliminated",
                            Name = "Layoff"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Performance issues",
                            Name = "Performance"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Employee retired",
                            Name = "Retirement"
                        });
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.VeteranStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VeteranStatusTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No military service",
                            Name = "Not a Veteran"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Military service veteran",
                            Name = "Veteran"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Disabled military service veteran",
                            Name = "Disabled Veteran"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Currently in military reserves",
                            Name = "Active Reserve"
                        });
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.WorkStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "40 hours per week",
                            Name = "Full-Time"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Less than 40 hours per week",
                            Name = "Part-Time"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Temporary contract worker",
                            Name = "Contract"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Seasonal employee",
                            Name = "Seasonal"
                        });
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.Employee", b =>
                {
                    b.HasOne("CrewChange.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany("Employees")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.EmployeeGroup", "EmployeeGroup")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.EmployeeScheduleType", "EmployeeScheduleType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeScheduleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.EmployeeStatus", "EmployeeStatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.WorkStatus", "EmployeeWorkStatus")
                        .WithMany("EmployeeWorkStatuses")
                        .HasForeignKey("EmployeeWorkStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.GenderType", "GenderType")
                        .WithMany("Employees")
                        .HasForeignKey("GenderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.Job", "Job")
                        .WithMany("Employees")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.MaritalStatus", "MaritalStatus")
                        .WithMany("Employees")
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.NationalityType", "NationalityType")
                        .WithMany("Employees")
                        .HasForeignKey("NationalityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.State", "State")
                        .WithMany("Employees")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.TerminationReason", "TerminationReason")
                        .WithMany("Employees")
                        .HasForeignKey("TerminationReasonId");

                    b.HasOne("CrewChange.Domain.Entities.VeteranStatusType", "VeteranStatusType")
                        .WithMany("Employees")
                        .HasForeignKey("VeteranStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewChange.Domain.Entities.WorkStatus", "WorkStatus")
                        .WithMany("Employees")
                        .HasForeignKey("WorkStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("EmployeeGroup");

                    b.Navigation("EmployeeScheduleType");

                    b.Navigation("EmployeeStatus");

                    b.Navigation("EmployeeWorkStatus");

                    b.Navigation("GenderType");

                    b.Navigation("Job");

                    b.Navigation("Location");

                    b.Navigation("MaritalStatus");

                    b.Navigation("NationalityType");

                    b.Navigation("State");

                    b.Navigation("TerminationReason");

                    b.Navigation("VeteranStatusType");

                    b.Navigation("WorkStatus");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EmployeeCertification", b =>
                {
                    b.HasOne("CrewChange.Domain.Entities.Employee", "Employee")
                        .WithMany("Certifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.Location", b =>
                {
                    b.HasOne("CrewChange.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EducationLevel", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Certifications");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EmployeeGroup", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EmployeeScheduleType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.EmployeeStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.GenderType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.Job", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.Location", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.MaritalStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.NationalityType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.State", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.TerminationReason", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.VeteranStatusType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrewChange.Domain.Entities.WorkStatus", b =>
                {
                    b.Navigation("EmployeeWorkStatuses");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
